DEFAULT_ANNUAL_INCOME = 100000

DEFAULT_CURRENCY = "EUR"

DEFAULT_CURRENCY_LIST = ["EUR", "USD", "GBP", "CHF", "JPY", "CAD", "AUD", "NZD"]

DEFAULT_CATEGORIES = ["Luxury", "Essentials", "Savings", "Investments"]

DEFAULT_MONTHLY_BUDGET = round(DEFAULT_ANNUAL_INCOME/12,2)

DEFAULT_MONTHLY_FIXED_EXPENSES = -2000

DEFAULT_MONTHLY_BALANCE = DEFAULT_MONTHLY_BUDGET + DEFAULT_MONTHLY_FIXED_EXPENSES