DEFAULT_ANNUAL_INCOME = 100000

DEFAULT_CURRENCY = "EUR"

DEFAULT_CURRENCY_LIST = ["EUR", "USD", "GBP", "CHF", "JPY", "CAD", "AUD", "NZD"]

DEFAULT_CATEGORIES = ["Luxury", "Essentials", "Savings", "Investments"]